version: "3.8"

services:
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6380:6380"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data
  api:
    build:
      context: .
      target: development
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    command: npm run dev

volumes:
  cache:
    driver: local
